Repository arygm/QuickFix, pull requests merged in 2024-12, with the labels that each got.

#183 implement the search location screen
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/LocationSearchCustomScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/locations/Location.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixSearchLocation.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/java/com/arygm/quickfix/ui/search/Announcement.kt
  app/src/test/java/com/arygm/quickfix/ui/navigation/NavigationActionsTest.kt
  gradle/libs.versions.toml
Labels: enhancement, prio:high

#184 Backend/userprofile workerprofile refactor 2
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/BusinessScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/ProfessionalInfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/QuickFixFinderScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchCategoryButtonTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchOnBoardingTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryRepository.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/dataFields/Service.kt
  app/src/main/java/com/arygm/quickfix/model/profile/dataFields/ServiceSubgroups.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFix.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFixRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/service/Service.kt
  app/src/main/java/com/arygm/quickfix/ressources/C.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixCheckedListElement.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/PersonalInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/ProfessionalInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/search/QuickFixFinder.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchOnBoarding.kt
  app/src/test/java/com/arygm/quickfix/model/categories/CategoryViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/quickfix/QuickFixRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/quickfix/QuickFixViewModelTest.kt
Labels: enhancement, prio:high, UI, backend

#185 Add Availability Worker Filtering in SearchWorkerResult screen
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/test/java/com/arygm/quickfix/model/search/WorkerFilterTest.kt
Labels: prio:high, feature, UI, backend

#195 Add service type filtering and Rating Sorting
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/ChooseServiceTypeSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixServicesChoosing.kt
  app/src/main/java/com/arygm/quickfix/ui/search/ExpandableCategoryItem.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/test/java/com/arygm/quickfix/model/search/WorkerFilterTest.kt
Labels: enhancement, prio:high, feature, UI, backend

#174 Update of the profileScreen UI
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/ProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/search/Announcement.kt
Labels: enhancement, UI

#176 feat: start implementation of QuickFixFirstStep screen
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixCheckedListElementTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDateTimePickerTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/ProfessionalInfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchOnBoardingTest.kt
  app/src/main/java/com/arygm/quickfix/model/locations/LocationViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/DashBorder.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixButton.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixCheckedListElement.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixDateTimePicker.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStep.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchOnBoarding.kt
  app/src/main/java/com/arygm/quickfix/ui/test.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Color.kt
  gradle/libs.versions.toml
Labels: feature, UI

#197 Backend/userprofile workerprofile refactor 3
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/BusinessScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/ProfessionalInfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/QuickFixCheckedListElementTest.kt
  app/src/main/java/com/arygm/quickfix/ressources/C.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixCheckedListElement.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/ProfessionalInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/QuickFixCheckedList.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStep.kt
  app/src/main/res/drawable/onboarding_worker_1.png
Labels: prio:high, feature, UI

#202 Add QuickFixPriceRange element and Bottom Sheet and Price Range Filter
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixPriceRangeBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixPriceRangeTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixPriceRange.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixPriceRangeBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/test/java/com/arygm/quickfix/model/search/WorkerFilterTest.kt
Labels: prio:high, feature, UI, backend

#203 Integrate Camera and Gallery Functionality in the Announcement Process
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ui/camera/QuickFixDisplayImagesTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/camera/QuickFixUploadImageSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixUploadImageTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/PersonalInfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementRepository.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/camera/QuickFixDisplayImages.kt
  app/src/main/java/com/arygm/quickfix/ui/camera/QuickFixUploadImage.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/PersonalInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/search/QuickFixFinder.kt
  app/src/main/res/drawable/flipcamera.xml
  app/src/main/res/drawable/selectimages.xml
  app/src/test/java/com/arygm/quickfix/model/search/AnnouncementRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/search/AnnouncementViewModelTest.kt
  gradle/libs.versions.toml
Labels: prio:high, feature, UI, backend

#211 [Offline Mode] - Implement helper functions to interface DataStore
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileConfigurationScreenTest.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/GoogleInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/AccountConfiguration.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/ProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/utils/Preferences.kt
  app/src/test/java/com/arygm/quickfix/utils/PreferencesTest.kt
Labels: enhancement, prio:high, backend

#212 task: add offline bar element and implement it with main activity
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixOfflineBarTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixOfflineBar.kt
Labels: enhancement, prio:high, UI

#208 feat: Add tests and components for QuickFix Details and Sliding Window
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDetailsScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixSlidingWindowContentTest.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixDetailsdescription.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixSlindingWindowWithContent.kt
Labels: prio:high, feature, UI

#210 Location and Clear Filter
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/ChooseServiceTypeSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixPriceRangeBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixPriceRangeTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixPriceRange.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixPriceRangeBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixServicesChoosing.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/main/java/com/arygm/quickfix/utils/LocationHelper.kt
  app/src/test/java/com/arygm/quickfix/model/search/WorkerFilterTest.kt
Labels: enhancement, prio:high, feature, UI, backend

#215 Refine Filter Interactions and SearchViewModel and Filter Composables
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/ChooseServiceTypeSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDateTimePickerTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixServicesChoosing.kt
  app/src/main/java/com/arygm/quickfix/ui/search/ExpandableCategoryItem.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/main/java/com/arygm/quickfix/utils/String.kt
  app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/utils/StringTest.kt
Labels: enhancement, prio:high, UI, backend

#201 Backend/userprofile workerprofile refactor 4
  app/src/androidTest/java/com/arygm/quickfix/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/LogInScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/RegisterScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/WelcomeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/home/MessageScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/BusinessScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/PersonalInfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/ProfessionalInfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/welcome/WelcomeOnBoardScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/account/LoggedInAccountViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/locations/LocationViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileRepository.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/dataFields/Review.kt
  app/src/main/java/com/arygm/quickfix/model/profile/dataFields/ServiceSubgroups.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ressources/C.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/PersonalInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/ProfessionalInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/QuickFixCheckedList.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/welcome/WelcomeOnBoardScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStep.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/main/java/com/arygm/quickfix/utils/Preferences.kt
  app/src/test/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreTest.kt
  end2end-data/auth_export/accounts.json
  end2end-data/auth_export/config.json
  end2end-data/firebase-export-metadata.json
  end2end-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  end2end-data/firestore_export/all_namespaces/all_kinds/output-0
  end2end-data/firestore_export/firestore_export.overall_export_metadata
  firebase.json
  storage.rules
  upload_categories.py
Labels: enhancement, prio:high, meta, UI, backend

#218 backend: populate firestore worker
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDateTimePickerTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  populate_data/upload_categories.py
  populate_data/upload_workers.py
Labels: enhancement, prio:high, backend

#189 Feat: UI for searching tags
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDateTimePickerTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/ProfileResultsTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/QuickFixSlidingWindowWorkerTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchOnBoardingTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixServicesChoosing.kt
  app/src/main/java/com/arygm/quickfix/ui/search/CategoryContents.kt
  app/src/main/java/com/arygm/quickfix/ui/search/ExpandableCategoryItem.kt
  app/src/main/java/com/arygm/quickfix/ui/search/ProfileResults.kt
  app/src/main/java/com/arygm/quickfix/ui/search/QuickFixFinder.kt
  app/src/main/java/com/arygm/quickfix/ui/search/QuickFixSlidingWindowWorker.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchOnBoarding.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
Labels: feature, UI

#216 feat: Refactor messaging system and improve UI tests
  app/src/androidTest/java/com/arygm/quickfix/ui/home/MessageScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/Chat.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepository.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/Message.kt
  app/src/main/java/com/arygm/quickfix/ui/home/MessagesScreen.kt
  app/src/test/java/com/arygm/quickfix/model/messaging/ChatRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/messaging/ChatViewModelTest.kt
Labels: enhancement, prio:high, UI, backend

#221 Complete Third Step of Onboarding Process (Worker View) and Add/Refactor Tests
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDetailsScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixSlidingWindowContentTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixSecondStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixThirdStepTest.kt
  app/src/main/java/com/arygm/quickfix/model/bill/BillField.kt
  app/src/main/java/com/arygm/quickfix/model/bill/Unit.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFix.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFixRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixSlindingWindowWithContent.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStep.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixSecondStep.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixThirdStep.kt
  app/src/main/res/drawable/calendar_today.xml
  app/src/test/java/com/arygm/quickfix/model/quickfix/QuickFixRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/quickfix/QuickFixViewModelTest.kt
Labels: enhancement, feature, UI, backend

#224 Add Final Step of Onboarding Process, Update Tests, Refactor Old Ones, and Update E2E Data
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDateTimePickerTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixWorkerOverviewTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/home/MessageScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixLastStepTest.kt
  app/src/main/java/com/arygm/quickfix/model/categories/Category.kt
  app/src/main/java/com/arygm/quickfix/model/categories/WorkerCategory.kt
  app/src/main/java/com/arygm/quickfix/model/categories/painting/PaintinCategory.kt
  app/src/main/java/com/arygm/quickfix/model/categories/plumbing/PlumbingCategory.kt
  app/src/main/java/com/arygm/quickfix/model/category/Category.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryRepository.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/dataFields/Review.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFix.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixWorkerOverview.kt
  app/src/main/java/com/arygm/quickfix/ui/home/MessagesScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStep.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixLastStep.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixThirdStep.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerProfileResult.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/test/java/com/arygm/quickfix/model/categories/PaintingSubCategoryTest.kt
  app/src/test/java/com/arygm/quickfix/model/categories/PlumbingCategoryTest.kt
  app/src/test/java/com/arygm/quickfix/model/categories/PlumbingSubCategoryTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreTest.kt
  end2end-data/auth_export/accounts.json
  end2end-data/firebase-export-metadata.json
  end2end-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  end2end-data/firestore_export/all_namespaces/all_kinds/output-0
  end2end-data/firestore_export/firestore_export.overall_export_metadata
  gradle/libs.versions.toml
  populate_data/upload_categories.py
  settings.gradle.kts
Labels: enhancement, feature, UI, backend

#217 Search Engine Function, Search Flow Bug Fix, Quality of life updates
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixStarRatingTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixWorkerOverviewTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixLastStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/dataFields/Review.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixPriceRange.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixPriceRangeBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixStarRating.kt
  app/src/main/java/com/arygm/quickfix/ui/quickfix/QuickFixLastStep.kt
  app/src/main/java/com/arygm/quickfix/ui/search/ExpandableCategoryItem.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerProfileResult.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/main/java/com/arygm/quickfix/utils/GeocoderWrapper.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreTest.kt
Labels: enhancement, prio:high, feature, UI, backend

#233 Re-adding Deleted Changes
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/ExpandableCategoryItem.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerResult.kt
Labels: bug, prio:high

#234 [Offline Mode] - Implement chat caching using Room
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ui/home/MessageUserNoModeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/Chat.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepository.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/offline/large/Converters.kt
  app/src/main/java/com/arygm/quickfix/model/offline/large/QuickFixRoomDatabase.kt
  app/src/main/java/com/arygm/quickfix/model/offline/large/messaging/ChatDao.kt
  app/src/main/java/com/arygm/quickfix/model/offline/large/messaging/ChatEntity.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/noModeUI/authentication/WelcomeScreen.kt
  app/src/test/java/com/arygm/quickfix/model/messaging/ChatRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/messaging/ChatViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/offline/large/ConvertersTest.kt
  app/src/test/java/com/arygm/quickfix/model/offline/large/QuickFixRoomDatabaseTest.kt
  app/src/test/java/com/arygm/quickfix/model/offline/large/messaging/ChatDaoTest.kt
  app/src/test/java/com/arygm/quickfix/model/offline/large/messaging/ChatEntityTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: prio:high, feature, backend

#235 feat: Update Announcement Screen design and add new fields
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementUserNoModeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/QuickFixFinder.kt
Labels: enhancement, prio:high

#240 Enhanced Mode Switching Functionality and Code Refactoring profile screen worker
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileConfigurationUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileUserNoModeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/switchModes/ModeViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixProfileElement.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixProfileSectionElement.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/AppContentNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/AccountConfiguration.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/UserProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/WorkerModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/navigation/WorkerNavigation.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/profile/ProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/profile/WorkerProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/utils/Preferences.kt
Labels: enhancement, prio:high, UI, backend

#244 Add announcement process to dashboard and skeleton for announcement detail screen
  app/src/androidTest/java/com/arygm/quickfix/ui/camera/QuickFixDisplayImagesTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/AnnouncementsWidgetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/DashboardScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/DashboardUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementDetailTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/QuickFixFinderScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/QuickFixFinderUserNoModeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementRepository.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/AnnouncementsWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixSearchLocation.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/camera/QuickFixDisplayImages.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/dashboard/Dashboard.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/navigation/UserNavigation.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/AnnouncementDetail.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/QuickFixFinder.kt
  app/src/main/res/drawable/delete.xml
  app/src/main/res/drawable/edit.xml
  app/src/test/java/com/arygm/quickfix/model/search/AnnouncementRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/search/AnnouncementViewModelTest.kt
Labels: enhancement, prio:high, UI, backend

#242 Connect backend to Dashboard screen and add QuickFix widgets to Home screen
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/HomeUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/camera/QuickFixDisplayImagesTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/BillsWidgetTests.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/DashboardScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/MessageWidgetTests.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/UpcomingQuickFixesTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementDetailTest.kt
  app/src/main/java/com/arygm/quickfix/model/account/AccountRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepository.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/Message.kt
  app/src/main/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFixViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixesWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/camera/QuickFixDisplayImages.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/dashboard/BillsWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/dashboard/ChatWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/dashboard/Dashboard.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/AnnouncementDetail.kt
  end2end-data/storage_export/blobs/702c0558-bd86-438b-90df-670579ada7d3
  end2end-data/storage_export/metadata/702c0558-bd86-438b-90df-670579ada7d3.json
Labels: enhancement, feature, backend

#254 Add Detailed Announcement View
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementDetailTest.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/AnnouncementDetail.kt
Labels: prio:high, feature, UI

#250 feat: Add image display tests and enhance QuickFix UI components
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDetailsUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDisplayImagesScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixSlidingWindowContentTest.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixDetailsdescription.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixFetchQuickFixImages.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixSlindingWindowWithContent.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/MessagesScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/navigation/UserNavigation.kt
Labels: enhancement, prio:high, UI

#237 Link Search Engine and Fix UI Bugs
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/ProfileResultsTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/QuickFixFinderScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchOnBoardingTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixSlidingWindow.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/CategoryContents.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/ProfileResults.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/QuickFixFinder.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/QuickFixSlidingWindowWorker.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchOnBoarding.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerProfileResult.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerResult.kt
Labels: prio:high, feature, UI, backend

#256 [Offline Mode] - Add support for caching categories
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixLastStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementDetailTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/category/Category.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryRepository.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/offline/large/Converters.kt
  app/src/main/java/com/arygm/quickfix/model/offline/large/QuickFixRoomDatabase.kt
  app/src/main/java/com/arygm/quickfix/model/offline/large/categories/CategoryDao.kt
  app/src/main/java/com/arygm/quickfix/model/offline/large/categories/CategoryEntity.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/AnnouncementsWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/dashboard/ChatWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/AnnouncementDetail.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/QuickFixFinder.kt
  app/src/test/java/com/arygm/quickfix/model/category/CategoryTest.kt
  app/src/test/java/com/arygm/quickfix/model/category/CategoryViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/offline/large/ConvertersTest.kt
  app/src/test/java/com/arygm/quickfix/model/offline/large/QuickFixRoomDatabaseTest.kt
  app/src/test/java/com/arygm/quickfix/model/offline/large/categories/CategoryDaoTest.kt
  app/src/test/java/com/arygm/quickfix/model/offline/large/categories/CategoryEntityTest.kt
Labels: enhancement, prio:high, backend

#259 [UI] - Fix bottom navigation bar visual bug
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/CategoryContents.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/WorkerModeNavGraph.kt
Labels: bug, prio:high, UI

#263 [Toolbox] - Add the toolbox floating button
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/HomeUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixToolboxFloatingButtonTest.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixToolboxFloatingButton.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt
Labels: prio:high, feature, UI

#247 Implement EarningsWidget
  app/src/androidTest/java/com/arygm/quickfix/ui/home/EarningsWidgetTest.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/home/EarningsWidget.kt
Labels: feature, UI

#266 [Bug] - Reposition floating button in home screen
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt
Labels: bug, enhancement, prio:high, UI

#246 Refactor: Account configuration screen and related components
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileConfigurationUserNoModeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/account/Account.kt
  app/src/main/java/com/arygm/quickfix/model/account/AccountRepository.kt
  app/src/main/java/com/arygm/quickfix/model/account/AccountRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/account/AccountViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/offline/small/PreferencesViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/AccountConfiguration.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/utils/Preferences.kt
  app/src/test/java/com/arygm/quickfix/model/account/AccountRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/account/AccountViewModelTest.kt
Labels: enhancement, prio:high, UI

#268 [Tools] - Add functionning AI Chat Bot
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ui/tools/ai/QuickFixAIChatScreenTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arygm/quickfix/model/tools/ai/GeminiMessageModel.kt
  app/src/main/java/com/arygm/quickfix/model/tools/ai/GeminiViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/tools/ai/QuickFixAIChatScreen.kt
  app/src/test/java/com/arygm/quickfix/model/tools/ai/QuickFixViewModelTest.kt
  gradle/libs.versions.toml
Labels: prio:high, feature, UI, backend

#269 Worker Announcements View Implementation
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementCardTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementDetailTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementsScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementRepository.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/AnnouncementsWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/AppContentNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerResult.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/WorkerModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/announcements/AnnouncementCard.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/announcements/AnnouncementsScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/navigation/WorkerNavigation.kt
  app/src/test/java/com/arygm/quickfix/model/search/AnnouncementRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/search/AnnouncementViewModelTest.kt
Labels: prio:high, feature, UI, backend

#243 Add Profile Picture Fetching and Backend for Saved Lists
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/ProfileResultsTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/QuickFixFinderScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchOnBoardingTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerProfileResultTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileRepository.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/AppContentNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/navigation/UserNavigation.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/UserProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/ExpandableCategoryItem.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/ProfileResults.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/QuickFixFinder.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchOnBoarding.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerProfileResult.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerResult.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/WorkerModeNavGraph.kt
  app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestoreImageFetchTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreImageFetchTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreTest.kt
  end2end-data/auth_export/accounts.json
  end2end-data/firebase-export-metadata.json
  end2end-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  end2end-data/firestore_export/all_namespaces/all_kinds/output-0
  end2end-data/firestore_export/firestore_export.overall_export_metadata
  end2end-data/storage_export/blobs/702c0558-bd86-438b-90df-670579ada7d3
  end2end-data/storage_export/metadata/702c0558-bd86-438b-90df-670579ada7d3.json
  gradle/libs.versions.toml
  populate_data/upload_workers.py
Labels: enhancement, feature, backend

#258 Initial Implementation of Worker Mode and Interaction Features
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/HomeUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/BillsWidgetTests.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/DashboardScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/MessageWidgetTests.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDetailsUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixSlidingWindowContentTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/home/MessageUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixLastStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixSecondStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixThirdStepTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/offline/small/PreferencesViewModelWorkerProfile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFixRepository.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFixRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFixViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/AnnouncementsWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/BillsWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/ChatWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/Dashboard.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixDateTimePicker.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixDetailsdescription.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixProfileElement.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixSlindingWindowWithContent.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixStepper.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/ScrollableRow.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/AppContentNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/MessagesScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/UserProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/welcome/WelcomeOnBoardScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/quickfix/QuickFixFirstStep.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/quickfix/QuickFixLastStep.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/quickfix/QuickFixOnBoarding.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/quickfix/QuickFixSecondStep.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/quickfix/QuickFixThirdStep.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchOnBoarding.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerProfileResult.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerResult.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/WorkerModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/announcements/AnnouncementsScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/navigation/WorkerNavigation.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/profile/WorkerProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/quickfix/QuickFixBilling.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/noModeUI/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/utils/Preferences.kt
  app/src/main/res/drawable/noquickfix.xml
  app/src/test/java/com/arygm/quickfix/model/quickfix/QuickFixRepositoryFirestoreTest.kt
  end2end-data/storage_export/blobs/04b54809-5f17-4a98-a036-9da2ad69274f
  end2end-data/storage_export/blobs/9d6ec3de-086d-4117-b022-0fc31782bb85
  end2end-data/storage_export/metadata/04b54809-5f17-4a98-a036-9da2ad69274f.json
  end2end-data/storage_export/metadata/9d6ec3de-086d-4117-b022-0fc31782bb85.json
Labels: enhancement, feature, backend

#275 Search Engine Fix
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchOnBoarding.kt
  app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
Labels: enhancement, prio:high, backend

#252 feature: added working hours
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/PersonalInfoUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/professional/ProfessionalInfoUserNoModeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/personal/PersonalInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/professional/ProfessionalInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/professional/TimeDropDownMenu.kt
  end2end-data/storage_export/blobs/feefd070-24dd-49b1-afed-0da72158f85c
  end2end-data/storage_export/metadata/feefd070-24dd-49b1-afed-0da72158f85c.json
Labels: enhancement, prio:high, feature, UI

#262 Map Screen
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/map/MapScreenTest.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixToolboxFloatingButton.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/map/MapScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/navigation/UserNavigation.kt
  app/src/main/res/raw/alternate_map_style.json
  app/src/main/res/raw/map_style.json
Labels: prio:high, feature, UI

#291 [Refactor] - Remove deprecated and unused files
  app/src/main/java/com/arygm/quickfix/model/account/LoggedInAccountViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/LoggedInProfileViewModel.kt
Labels: documentation, prio:low, files, repository

#276 Home search and PopularService Navigation
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/HomeUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/ScrollableRowTest.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/ScrollableRow.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/CategoryContents.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/ExpandableCategoryItem.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchOnBoarding.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchWorkerResult.kt
Labels: prio:high, backend

#294 Remove the pen icon from the toolbox
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt
Labels: bug, enhancement, prio:high, UI

#295 [Bug] - fixed a bug in ChatWidget
  app/src/main/java/com/arygm/quickfix/ui/dashboard/ChatWidget.kt
Labels: bug, enhancement, prio:high, UI

#292 feature: switch worker button is responsive
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/welcome/WelcomeOnBoardUserNoModeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixProfileElement.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Color.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Theme.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/AppContentNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/map/MapScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/profile/becomeWorker/views/welcome/WelcomeOnBoardScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/WorkerModeNavGraph.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/profile/WorkerProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/uiMode/noModeUI/authentication/WelcomeScreen.kt
  app/src/main/res/drawable/no_quickfixes_dark.xml
  app/src/main/res/drawable/noquickfixdark.xml
Labels: enhancement, prio:low, feature
