Repository arygm/QuickFix, pull requests merged in 2024-11, with the labels that each got.

#107 ci: add task to run `connectedCheck` with Firebase emulators and upda…
  .github/workflows/CI.yaml
  app/build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: meta

#110 feat: Add GoogleInfoScreen and tests
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/GoogleInfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/GoogleInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/java/com/arygm/quickfix/utils/Authentication.kt
Labels: prio:high, feature, UI

#112 feat: add worker profile filtering and unit tests
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/searchViewModel.kt
  app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreTest.kt
Labels: backend

#106 Search screen
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/QuickFixTextFieldCustomTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/SearchScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchCategoryButtonTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchOnBoardingTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/Search.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LogInScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchCategoryButton.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchOnBoarding.kt
Labels: feature, UI

#114 fix: Fix Navigation Typo Regarding Google Sign In
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
Labels: prio:high, UI

#109 Refactor Home Screen to Include Popular Services and Upcoming QuickFixes
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/HomeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/ScrollableRowTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/UpcomingQuickFixesTest.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/ScrollableRow.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/UpcomingQuickFix.kt
  app/src/main/java/com/arygm/quickfix/ui/home/HomeScreen.kt
  app/src/main/res/drawable/electrician.png
  app/src/main/res/drawable/gardener.png
  app/src/main/res/drawable/mechanic.png
  app/src/main/res/drawable/painter.png
  app/src/main/res/drawable/plumber.png
Labels: prio:low, feature, UI

#117 fix: Fix the navigation where we inversed the logic
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
Labels: prio:high, UI

#121 96 announcement process
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/QuickFixFinderScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchOnBoardingTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/search/QuickFixFinder.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchOnBoarding.kt
Labels: prio:high, feature, UI

#125 ci: Add Windows compatibility for connectedCheckWithEmulators task
  app/build.gradle.kts
Labels: prio:high, meta

#128 Build Announcement Screen Based on Figma Design
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/search/Announcement.kt
  app/src/main/res/drawable/calendar.xml
  app/src/main/res/drawable/upload_image.xml
Labels: prio:high, feature, UI

#130 Enhance the bottom bar adaptability to navigation actions accross the app
  app/src/androidTest/java/com/arygm/quickfix/ui/search/QuickFixFinderScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/test/java/com/arygm/quickfix/ui/navigation/NavigationActionsTest.kt
Labels: enhancement, prio:high

#132 Announcement screen enhancement by adding upload image element
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixUploadImageTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixUploadImage.kt
  app/src/main/java/com/arygm/quickfix/ui/search/Announcement.kt
  app/src/main/res/drawable/camera.xml
Labels: enhancement, prio:high, feature, UI

#133 Manage categories with FireStore (uploading data)
  .gitignore
  app/src/main/java/com/arygm/quickfix/model/category/Category.kt
  upload_categories.py
Labels: prio:high, meta, backend

#116 backend: implement messaging backend
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/BusinessScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/account/Account.kt
  app/src/main/java/com/arygm/quickfix/model/account/AccountRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/location/Location.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/Chat.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepository.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/ChatViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/messaging/Message.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/searchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/utils/Authentication.kt
  app/src/main/java/com/arygm/quickfix/utils/Database.kt
  app/src/test/java/com/arygm/quickfix/model/account/LoggedInAccountViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/messaging/ChatRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/messaging/ChatViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/ProfileViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreTest.kt
Labels: prio:high, feature, backend

#127 feat: Add Phone GPS and Tests
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/utils/LocationHelper.kt
  app/src/test/java/com/arygm/quickfix/utils/LocationHelperTest.kt
  gradle/libs.versions.toml
Labels: prio:high, backend

#149 chore: refactor screens to support multiple screen sizes
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/WelcomeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/GoogleInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LogInScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/RegisterScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/ResetPasswordScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
Labels: enhancement, prio:high, UI

#155 chore: add app icon, app name and fix rotation to portrait
  app/src/main/AndroidManifest.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: prio:high, meta

#154 feat: Implement ChooseServiceTypeSheet and UI tests for service selection
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/ChooseServiceTypeSheetTest.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuiickFixServicesChoosing.kt
Labels: prio:high, feature, UI

#163 bug: fix typo in QuickFixServicesChoosing
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixServicesChoosing.kt
Labels: bug, prio:low, files

#166 Implement the announcement process backend
  app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/QuickFixFinderScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementRepository.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/search/AnnouncementViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/search/QuickFixFinder.kt
  app/src/main/java/com/arygm/quickfix/utils/Authentication.kt
  app/src/test/java/com/arygm/quickfix/model/account/LoggedInAccountViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/ProfileViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/search/AnnouncementRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/search/AnnouncementViewModelTest.kt
Labels: backend

#152 Implementation of the NominatimLocationRepository and LocationViewModel
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arygm/quickfix/model/locations/LocationRepository.kt
  app/src/main/java/com/arygm/quickfix/model/locations/LocationViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/locations/NominatimLocationRepository.kt
  app/src/test/java/com/arygm/quickfix/location/LocationViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/location/NominatimLocationRepositoryTest.kt
  gradle/libs.versions.toml
Labels: feature, backend

#164 feat: Implement worker profile sliding window
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixSlidingWindowTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixSlidingWindow.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerProfileResult.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/main/res/drawable/moroccan_flag.jpg
Labels: prio:high, feature, UI

#169 Clean up test files
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/LogInScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/ChooseServiceTypeSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixAnimatedBoxTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixUploadImageTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerListViewModelTest.kt
Labels: prio:low, files

#177 Enhance WorkerProfile Data Class and Upgrade Worker Onboarding Flow
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/BusinessScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/BusinessScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/CameraBottomSheetTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/FakePermissionState.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/MockLifecycleOwner.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/PersonalInfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/TestActivityResultLauncher.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchCategoryButtonTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/account/AccountRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/category/Category.kt
  app/src/main/java/com/arygm/quickfix/model/category/CategoryRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/dataFields/Review.kt
  app/src/main/java/com/arygm/quickfix/model/profile/dataFields/Service.kt
  app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
  app/src/main/java/com/arygm/quickfix/ressources/C.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LogInScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/RegisterScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixButton.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/AccountConfiguration.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/CameraBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/becomeWorker/views/personal/PersonalInfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/search/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchOnBoarding.kt
  app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
  app/src/main/java/com/arygm/quickfix/ui/test.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Color.kt
  app/src/main/res/xml/file_path.xml
  app/src/test/java/com/arygm/quickfix/model/account/LoggedInAccountViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreTest.kt
  gradle/libs.versions.toml
  upload_categories.py
Labels: enhancement, prio:high, UI, backend

#171 feat: QuickFix Class and Repository and ViewModel
  app/src/main/java/com/arygm/quickfix/model/account/AccountRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/bill/BillField.kt
  app/src/main/java/com/arygm/quickfix/model/bill/Unit.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFix.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFixRepository.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFixRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/quickfix/QuickFixViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/service/Service.kt
  app/src/main/java/com/arygm/quickfix/model/service/ServiceSubgroups.kt
  app/src/test/java/com/arygm/quickfix/model/quickfix/QuickFixRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/quickfix/QuickFixViewModelTest.kt
Labels: prio:high, backend

#170 Dashboard screen UI
  app/src/androidTest/java/com/arygm/quickfix/ui/DashboardScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/BillsWidgetTests.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/DashboardScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/dashboard/MessageWidgetTests.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/UpcomingQuickFixesTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/Dashboard.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/BillsWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/Dashboard.kt
  app/src/main/java/com/arygm/quickfix/ui/dashboard/MessagesWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixButton.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixesWidget.kt
  app/src/main/java/com/arygm/quickfix/ui/home/HomeScreen.kt
Labels: prio:high, feature, UI

#165 Availability Bottom Sheet
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheetTest.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheet.kt
  app/src/main/java/com/arygm/quickfix/utils/MyAppTheme.kt
  gradle/libs.versions.toml
Labels: prio:high, UI
