Repository arygm/QuickFix, pull requests merged in 2024-10, with the labels that each got.

#3 Add files via upload
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/arygm/QuickFix/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/arygm/QuickFix/screen/MainScreen.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arygm/QuickFix/MainActivity.kt
  app/src/main/java/com/arygm/QuickFix/SecondActivity.kt
  app/src/main/java/com/arygm/QuickFix/SimpleData.kt
  app/src/main/java/com/arygm/QuickFix/resources/C.kt
  app/src/main/java/com/arygm/QuickFix/ui/theme/Color.kt
  app/src/main/java/com/arygm/QuickFix/ui/theme/Theme.kt
  app/src/main/java/com/arygm/QuickFix/ui/theme/Type.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/arygm/QuickFix/ExampleRobolectricTest.kt
  app/src/test/java/com/arygm/QuickFix/ExampleUnitTest.kt
  app/src/test/java/com/arygm/QuickFix/PointTest.kt
  app/src/test/java/com/arygm/QuickFix/screen/SecondScreen.kt
  app/src/test/resources/robolectric.properties
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: prio:high, files

#6 chore: add .gitignore files
  .gitignore
  app/.gitignore
Labels: prio:high, meta

#7 refactor: change package names
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/arygm/quickfix/screen/MainScreen.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/SecondActivity.kt
  app/src/main/java/com/arygm/quickfix/SimpleData.kt
  app/src/main/java/com/arygm/quickfix/resources/C.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Color.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Theme.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Type.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/arygm/quickfix/ExampleRobolectricTest.kt
  app/src/test/java/com/arygm/quickfix/ExampleUnitTest.kt
  app/src/test/java/com/arygm/quickfix/PointTest.kt
  app/src/test/java/com/arygm/quickfix/screen/SecondScreen.kt
  settings.gradle.kts
Labels: prio:high, meta, files

#8 chore: add Google Mobile Services (GMS) and Firebase dependencies
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: prio:high, meta

#5 Update README.md
  README.md
Labels: documentation, prio:low

#12 Add authentication UI
  app/src/main/java/com/arygm/quickfix/ui/authentication/LoginScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/PasswordScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/RegistrationScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
Labels: prio:high, feature, UI

#14 add: Add NavigationActions and MainActivity
  app/build.gradle.kts
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LoginScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/PasswordScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/RegistrationScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/res/drawable/dark_google_logo.png
  app/src/main/res/drawable/dark_quickfix_logo.png
  app/src/main/res/drawable/light_google_logo.png
  app/src/main/res/drawable/light_quickfix_logo.png
  app/src/main/res/drawable/worker_image.png
  gradle/libs.versions.toml
Labels: prio:high, feature, UI

#23 chore(ci): set up continuous integration workflow
  .github/workflows/CI.yaml
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/arygm/quickfix/screen/SecondScreen.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LoginScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/PasswordScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/RegistrationScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: prio:high, meta

#25 chore: resolve conflicts during rebase on main
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: meta

#32 Implement animated bottom navigation bar and integrate screens and navigation from mohagpt
  app/build.gradle.kts
  app/libs/meow-bottom-navigation-1.3.1.aar
  app/libs/meow-bottom-navigation-java-1.2.0.aar
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/Activity.kt
  app/src/main/java/com/arygm/quickfix/ui/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/Calendar.kt
  app/src/main/java/com/arygm/quickfix/ui/Home.kt
  app/src/main/java/com/arygm/quickfix/ui/Map.kt
  app/src/main/java/com/arygm/quickfix/ui/MeowBottomNavigationBar.kt
  app/src/main/java/com/arygm/quickfix/ui/Other.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/res/drawable/icon_annoucement.png
  app/src/main/res/drawable/icon_calendar.png
  app/src/main/res/drawable/icon_home.png
  app/src/main/res/drawable/icon_map.png
  app/src/main/res/drawable/icon_menu.png
  app/src/main/res/drawable/icon_other.png
  gradle.properties
  settings.gradle.kts
Labels: prio:high, feature, UI

#35 chore: add Mockito and Mockk libraries for unit and UI testing
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: prio:high, meta

#41 Authetication testing
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/LoginScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/PasswordScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/WelcomeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/InfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LoginScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/PasswordScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixAnimatedBox.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixBackButtonTopBar.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixCheckBoxRow.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextField.kt
  app/src/test/java/com/arygm/quickfix/utils/LoginTest.kt
  gradle/libs.versions.toml
Labels: prio:high, UI

#42 ci: update SonarCloud command to include additional checks and reports
  .github/workflows/CI.yaml
Labels: prio:high, meta

#43 test: Add Nav-Actions Test
  app/build.gradle.kts
  app/src/main/java/com/arygm/quickfix/ui/authentication/LoginScreen.kt
  app/src/test/java/com/arygm/quickfix/ui/navigation/NavigationActionsTest.kt
Labels: prio:high, UI, backend

#47 test: Add UI tests
  app/src/androidTest/java/com/arygm/quickfix/ui/ActivityScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/AnnouncementScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/CalendarScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/MapScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/OtherScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/PasswordScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixMainTopBarTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/home/HomeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/Activity.kt
  app/src/main/java/com/arygm/quickfix/ui/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/Calendar.kt
  app/src/main/java/com/arygm/quickfix/ui/Map.kt
  app/src/main/java/com/arygm/quickfix/ui/Other.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/PasswordScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixMainTopBar.kt
  app/src/main/java/com/arygm/quickfix/ui/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/test/java/com/arygm/quickfix/ui/navigation/BottomNavigationMenuTest.kt
Labels: prio:high, UI

#57 style: update QuickFix theme and UI components
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/LogInScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/theme/QuickFixTypographyTest.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LogInScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LoginScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixBackButtonTopBar.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixButton.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextField.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Color.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Theme.kt
  app/src/main/res/drawable/worker_image.png
  app/src/main/res/font/inter_extrabold.ttf
  app/src/main/res/font/inter_extrabolditalic.ttf
  app/src/main/res/font/poppins_black.ttf
  app/src/main/res/font/poppins_blackitalic.ttf
  app/src/main/res/font/poppins_bold.ttf
  app/src/main/res/font/poppins_bolditalic.ttf
  app/src/main/res/font/poppins_extrabold.ttf
  app/src/main/res/font/poppins_extrabolditalic.ttf
  app/src/main/res/font/poppins_extralight.ttf
  app/src/main/res/font/poppins_extralightitalic.ttf
  app/src/main/res/font/poppins_italic.ttf
  app/src/main/res/font/poppins_light.ttf
  app/src/main/res/font/poppins_lightitalic.ttf
  app/src/main/res/font/poppins_medium.ttf
  app/src/main/res/font/poppins_mediumitalic.ttf
  app/src/main/res/font/poppins_regular.ttf
  app/src/main/res/font/poppins_semibold.ttf
  app/src/main/res/font/poppins_semibolditalic.ttf
  app/src/main/res/font/poppins_thin.ttf
  app/src/main/res/font/poppins_thinitalic.ttf
  gradle/libs.versions.toml
Labels: enhancement, prio:high, UI

#65 fix: solve bug with animations
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/ActivityScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/AnnouncementScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/CalendarScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/MapScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/OtherScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/LogInScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/home/HomeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/Activity.kt
  app/src/main/java/com/arygm/quickfix/ui/Announcement.kt
  app/src/main/java/com/arygm/quickfix/ui/Calendar.kt
  app/src/main/java/com/arygm/quickfix/ui/Map.kt
  app/src/main/java/com/arygm/quickfix/ui/Other.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/InfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LogInScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
Labels: bug, enhancement, prio:high, UI

#49 feat: Add Profile Repo And User Sign In
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/LogInScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/PasswordScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/WelcomeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileRepository.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/RegistrationViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/InfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LogInScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/PasswordScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/utils/Authentication.kt
  app/src/main/java/com/arygm/quickfix/utils/Login.kt
  app/src/main/java/com/arygm/quickfix/utils/String.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/arygm/quickfix/model/profile/ProfileRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/ProfileViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/RegistrationViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/utils/CreateAccountWithEmailAndPasswordTest.kt
  app/src/test/java/com/arygm/quickfix/utils/LoginTest.kt
  app/src/test/java/com/arygm/quickfix/utils/SignInWithEmailAndPasswordTest.kt
  app/src/test/java/com/arygm/quickfix/utils/StringTest.kt
  gradle/libs.versions.toml
Labels: prio:high, feature, backend

#66 bug: fix bottom bar not appearing on some occasions
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/java/com/arygm/quickfix/utils/String.kt
  app/src/test/java/com/arygm/quickfix/utils/StringTest.kt
Labels: bug, prio:high, UI

#70 Implementation Register Screen
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/PasswordScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/RegisterScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/WelcomeScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/InfoScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LogInScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/PasswordScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/RegisterScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixCheckBoxRow.kt
  app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Theme.kt
Labels: enhancement, prio:high, UI

#80 52 edit profile screen
  app/src/androidTest/java/com/arygm/quickfix/ui/ProfileScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileConfigurationScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/ui/Profile.kt
  app/src/main/java/com/arygm/quickfix/ui/home/ProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/ProfileConfiguration.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/ProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/theme/Theme.kt
  app/src/main/java/com/arygm/quickfix/utils/String.kt
  app/src/main/res/drawable/accountsettingsvector.xml
  app/src/main/res/drawable/dashboardvector.xml
  app/src/main/res/drawable/helpvector.xml
  app/src/main/res/drawable/profilevector.xml
  app/src/main/res/drawable/wallletvector.xml
  app/src/main/res/drawable/workvector.xml
  app/src/test/java/com/arygm/quickfix/ui/navigation/NavigationActionsTest.kt
Labels: prio:high, UI

#81 Start business screen
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/UpgradetoWorkerScreenTest.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/UpgradeToWorkerScreen.kt
Labels: prio:high, feature, UI

#79 ci: add GitHub Actions workflow for building APK
  .github/workflows/android.yaml
  app/build.gradle.kts
Labels: prio:high, meta

#91 Separate Users and Workers and adapt classes
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/InfoScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/LogInScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/PasswordScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/RegisterScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/authentication/WelcomeScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileConfigurationScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/arygm/quickfix/ui/profile/UpgradetoWorkerScreenTest.kt
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/profile/LoggedInProfileViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerListViewModel.kt
  app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LogInScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/PasswordScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/RegisterScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/ProfileConfiguration.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/ProfileScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/profile/UpgradeToWorkerScreen.kt
  app/src/main/java/com/arygm/quickfix/utils/Authentication.kt
  app/src/test/java/com/arygm/quickfix/model/profile/ProfileViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/UserProfileRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerListViewModelTest.kt
  app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreTest.kt
  app/src/test/java/com/arygm/quickfix/utils/CreateAccountWithEmailAndPasswordTest.kt
  app/src/test/java/com/arygm/quickfix/utils/SignInWithEmailAndPasswordTest.kt
Labels: enhancement, prio:high, backend

#89 feat(navigation): Add multiple back stack support for top-level desti…
  .firebaserc
  .github/workflows/CI.yaml
  app/build.gradle.kts
  app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/arygm/quickfix/MainActivity.kt
  app/src/main/java/com/arygm/quickfix/model/profile/ProfileViewModel.kt
  app/src/main/java/com/arygm/quickfix/ui/authentication/LogInScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/home/HomeScreen.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/arygm/quickfix/ui/navigation/NavigationActions.kt
  app/src/main/java/com/arygm/quickfix/utils/Authentication.kt
  app/src/main/res/xml/network_security_config.xml
  emulator-data/auth_export/accounts.json
  emulator-data/auth_export/config.json
  emulator-data/firebase-export-metadata.json
  emulator-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  emulator-data/firestore_export/all_namespaces/all_kinds/output-0
  emulator-data/firestore_export/firestore_export.overall_export_metadata
  end2end-data/auth_export/accounts.json
  end2end-data/auth_export/config.json
  end2end-data/firebase-export-metadata.json
  end2end-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  end2end-data/firestore_export/all_namespaces/all_kinds/output-0
  end2end-data/firestore_export/firestore_export.overall_export_metadata
  firebase.json
Labels: prio:high, UI
